export interface IconData {
  filename: string;
  description: string;
  title: string;
  tag: string;
}

const iconData: IconData[] = [
  { filename: 'mapleleaf.png', description: '枫叶为掌状复叶，秋季因叶绿素分解，呈现红、橙、黄等色彩，色泽艳丽，是典型的秋季观赏植物。', title: '枫叶', tag: '植物' },
  { filename: 'apple.png', description: '苹果是一种常见的水果，富含维生素和膳食纤维，口感脆甜多汁，是全球广泛种植和消费的果品。', title: '苹果', tag: '水果' },
  { filename: 'ice_cream.png', description: '冰淇淋是一种冷冻甜点，主要由牛奶、糖和香料制成，口感绵密，风味多样，深受人们喜爱。', title: '冰淇淋', tag: '甜点' },
  { filename: 'parrot.png', description: '鹦鹉是色彩鲜艳的鸟类，以其模仿人类语言的能力而闻名。它们通常生活在热带和亚热带地区，是受欢迎的宠物。', title: '鹦鹉', tag: '鸟类' },
  { filename: 'umbrella.png', description: '雨伞是一种用于遮雨或遮阳的日常用品，通常由伞骨和伞布构成，结构轻便，易于携带。', title: '雨伞', tag: '雨具' },
  { filename: 'brain.png', description: '大脑是中枢神经系统的重要组成部分，负责控制身体的各项功能，包括思维、情感、记忆和运动。', title: '大脑', tag: '器官' },
  { filename: 'pineapple.png', description: '菠萝是一种热带水果，果肉香甜多汁，富含维生素C和菠萝蛋白酶，具有独特的风味。', title: '菠萝', tag: '水果' },
  { filename: 'skateboard.png', description: '滑板是一种流行运动工具，由一块木板和四个轮子组成，用于进行滑行和特技表演。', title: '滑板', tag: '器材' },
  { filename: 'dog.png', description: '狗是狗的幼崽，活泼可爱，忠诚友善，常被作为宠物饲养，给人们带来欢乐。', title: '狗', tag: '动物' },
  { filename: "bank.png", title: "银行", description: "银行是提供金融服务，如存款、贷款、支付和投资的机构，是现代经济中不可或缺的一部分。", tag: "金融,机构,经济" },
  { filename: "barber_tools.png", title: "理发工具", description: "理发工具包括剪刀、梳子、剃刀等，是理发师用于修剪和造型头发的专业设备。", tag: "理发,工具,美发" },
  { filename: "bath_mat_and_towel.png", title: "浴室垫和毛巾", description: "浴室垫通常放在浴室地面，用于吸水防滑；毛巾则用于擦拭身体，两者是浴室中常见的清洁用品。", tag: "浴室,家居,清洁" },
  { filename: "bicycle.png", title: "自行车", description: "自行车是一种人力驱动的交通工具，通过脚踏板驱动链条使车轮转动，具有环保、健康的特点。", tag: "交通工具,运动,环保" },
  { filename: "binoculars.png", title: "双筒望远镜", description: "双筒望远镜是一种光学仪器，通过两个平行的望远镜同时观察远处物体，提供立体视觉和放大效果。", tag: "光学仪器,观测,户外" },
  { filename: "bread.png", title: "面包", description: "面包是一种以谷物（通常是小麦粉）为主要原料，经过发酵、烘烤制成的食物，是世界各地的主食之一。", tag: "食物,主食,烘焙" },
  { filename: "bubble_tea.png", title: "珍珠奶茶", description: "珍珠奶茶是一种起源于台湾的饮品，以茶为基底，加入牛奶、珍珠（木薯粉圆）等配料，口感丰富。", tag: "饮品,台湾特色,奶茶" },
  { filename: "calligraphy_set.png", title: "书法套装", description: "书法套装通常包含毛笔、墨、砚台和纸，是练习书法艺术的必备工具，体现了中华传统文化。", tag: "书法,文化,艺术" },
  { filename: "canada_scene.png", title: "加拿大风光", description: "加拿大风光通常指加拿大境内的自然景观和人文建筑，包括山脉、湖泊、森林以及独特的城市风貌。", tag: "地理,旅游,加拿大" },
  { filename: "candle_making_kit.png", title: "蜡烛制作套装", description: "蜡烛制作套装包含制作蜡烛所需的蜡、烛芯、香精、模具等材料和工具，适合手工爱好者。", tag: "手工,DIY,蜡烛" },
  { filename: "cargo_plane.png", title: "货运飞机", description: "货运飞机是专门用于运输货物的大型飞机，具有载货量大、运输速度快的特点，是国际物流的重要组成部分。", tag: "航空,运输,物流" },
  { filename: "cash_register.png", title: "收银机", description: "收银机是商店中用于记录销售、计算价格和处理支付的设备，是零售业中不可或缺的工具。", tag: "零售,商业,设备" },
  { filename: "cat.png", title: "猫", description: "猫是一种小型哺乳动物，以其优雅、独立和可爱的特点而受到人类喜爱，常被作为宠物饲养。", tag: "宠物,动物,哺乳动物" },
  { filename: "ceiling_fan.png", title: "吊扇", description: "吊扇是一种安装在天花板上的电风扇，通过旋转叶片产生气流，用于室内通风和降温。", tag: "家电,家居,电器" },
  { filename: "chinese_brush.png", title: "毛笔", description: "毛笔是中国传统书写和绘画工具，以动物毛发制成，用于书法、国画等艺术创作。", tag: "文具,中国传统,艺术" },
  { filename: "cloud.png", title: "云", description: "云是大气中水蒸气凝结形成的可见水滴或冰晶集合体，形态各异，是天气变化的重要标志。", tag: "自然,天气,气象" },
  { filename: "comb.png", title: "梳子", description: "梳子是用于梳理头发的工具，通常由塑料、木材或金属制成，有助于整理发型和清洁头皮。", tag: "美发,个人护理,工具" },
  { filename: "deer.png", title: "鹿", description: "鹿是一种反刍哺乳动物，雄性通常有角，以其优美的姿态和温顺的性格而受到人们喜爱。", tag: "动物,野生动物,哺乳动物" },
  { filename: "desk_setup.png", title: "桌面布置", description: "桌面布置指办公桌或学习桌上的物品摆放和环境设置，旨在提高工作效率和舒适度。", tag: "办公,家居,效率" },
  { filename: "desktop_computer.png", title: "台式电脑", description: "台式电脑是放置在桌面使用的个人电脑，通常由主机、显示器、键盘和鼠标组成，性能强大。", tag: "电子产品,科技,办公" },
  { filename: "dump_truck.png", title: "自卸卡车", description: "自卸卡车是一种带有自动倾卸装置的卡车，主要用于运输散装物料，如沙土、石料等。", tag: "车辆,工程机械,运输" },
  { filename: "electric_scooter.png", title: "电动滑板车", description: "电动滑板车是一种以电力驱动的个人交通工具，轻便灵活，适合短途出行和休闲娱乐。", tag: "交通工具,电动,休闲" },
  { filename: "electric_skateboard.png", title: "电动滑板", description: "电动滑板是一种由电动机驱动的滑板，通过遥控器控制速度，为城市通勤和极限运动提供便利。", tag: "交通工具,运动,电动" },
  { filename: "engineering_tools.png", title: "工程工具", description: "工程工具是工程师在设计、建造和维护过程中使用的专业工具，种类繁多，涵盖测量、切割、组装等。", tag: "工具,工程,专业" },
  { filename: "ethiopian_landmarks.png", title: "埃塞俄比亚地标", description: "埃塞俄比亚地标是指埃塞俄比亚境内具有代表性的自然景观或人文建筑，如拉利贝拉岩石教堂、阿克苏姆方尖碑等。", tag: "地理,旅游,埃塞俄比亚" },
  { filename: "field_guide_book.png", title: "野外指南书", description: "野外指南书是一种用于识别野生动植物、矿物或自然现象的便携式书籍，常用于户外活动和科考。", tag: "书籍,户外,科普" },
  { filename: "firefighter_gear.png", title: "消防员装备", description: "消防员装备包括防火服、头盔、氧气瓶、灭火器等，旨在保护消防员在火灾现场的安全。", tag: "安全,职业,消防" },
  { filename: "firewood.png", title: "木柴", description: "木柴是用于燃烧的木材，常用于取暖、烹饪或篝火，是传统的燃料来源。", tag: "燃料,生活,户外" },
  { filename: "flower_painting.png", title: "花卉画", description: "花卉画是以花卉为主题的艺术作品，通过绘画形式展现花朵的美丽、色彩和生命力。", tag: "艺术,绘画,花卉" },
  { filename: "fried_chicken.png", title: "炸鸡", description: "炸鸡是将鸡肉块裹上面糊或面粉后油炸而成的食物，外酥里嫩，是世界各地广受欢迎的快餐。", tag: "食物,快餐,肉类" },
  { filename: "frog.png", title: "青蛙", description: "青蛙是一种两栖动物，通常生活在水边，以其跳跃能力和捕食昆虫的习性而闻名。", tag: "动物,两栖动物,自然" },
  { filename: "game_controller.png", title: "游戏手柄", description: "游戏手柄是电子游戏机的输入设备，用于控制游戏角色和操作，提供沉浸式游戏体验。", tag: "游戏,电子产品,娱乐" },
  { filename: "ghost.png", title: "幽灵", description: "幽灵是民间传说中死去的人的灵魂或幻影，常被描绘为透明、漂浮的形象，与神秘和恐怖相关。", tag: "传说,神秘,恐怖" },
  { filename: "glasses.png", title: "眼镜", description: "眼镜是用于矫正视力或保护眼睛的工具，通常由镜片和镜架组成，有多种类型和款式。", tag: "时尚,健康,配饰" },
  { filename: "hammer_drill.png", title: "电锤", description: "电锤是一种带有冲击功能的电动工具，适用于在混凝土、砖石等硬质材料上进行钻孔或凿削。", tag: "工具,电动工具,建筑" },
  { filename: "hiking_pole.png", title: "登山杖", description: "登山杖是登山和徒步运动中使用的辅助工具，用于增加平衡、减轻膝盖压力和提高行进效率。", tag: "户外,运动,登山" },
  { filename: "hookah.png", title: "水烟壶", description: "水烟壶是一种用于吸食烟草的器具，起源于中东，通过水过滤烟雾，常用于社交场合。", tag: "文化,器具,中东" },
  { filename: "house.png", title: "房屋", description: "房屋是供人类居住的建筑物，提供遮蔽、安全和舒适的私人空间，是家庭生活的重要场所。", tag: "建筑,居住,家居" },
  { filename: "india_scene.png", title: "印度风光", description: "印度风光展现了印度独特的自然景观、历史建筑和多元文化，如泰姬陵、恒河、色彩斑斓的市集等。", tag: "地理,旅游,印度" },
  { filename: "karaoke_machine.png", title: "卡拉OK机", description: "卡拉OK机是一种播放伴奏音乐并显示歌词的设备，供人们跟着音乐演唱，常用于娱乐聚会。", tag: "娱乐,音乐,聚会" },
  { filename: "kenya_scene.png", title: "肯尼亚风光", description: "肯尼亚风光通常指肯尼亚境内的自然景观和野生动物，如马赛马拉大草原、乞力马扎罗山以及各种野生动物。", tag: "地理,旅游,肯尼亚" },
  { filename: "kickstand.png", title: "支架", description: "支架是一种用于支撑自行车或摩托车直立的装置，方便停放，避免车辆倾倒。", tag: "自行车,摩托车,配件" },
  { filename: "kite.png", title: "风筝", description: "风筝是一种利用风力在空中飞行的玩具或运动器械，通常由骨架和轻质材料制成，造型多样。", tag: "玩具,运动,娱乐" },
  { filename: "komodo_dragon.png", title: "科莫多巨蜥", description: "科莫多巨蜥是世界上最大的蜥蜴，原产于印度尼西亚，以其强大的捕食能力和独特的外形而闻名。", tag: "动物,爬行动物,野生动物" },
  { filename: "landline_phone.png", title: "固定电话", description: "固定电话是使用电话线连接的通信设备，曾是主要的语音通信方式，如今仍广泛应用于家庭和办公室。", tag: "通信,电子产品,生活" },
  { filename: "lathe_machine.png", title: "车床", description: "车床是一种用于旋转工件并对其进行切削、钻孔、磨削等加工的机床，是机械加工的重要设备。", tag: "机械,工具,工业" },
  { filename: "light_switch.png", title: "电灯开关", description: "电灯开关是用于控制电路通断的装置，通过它可方便地开启或关闭电灯，是家居电器的基本组成部分。", tag: "家居,电器,电工" },
  { filename: "lotus_flower.png", title: "莲花", description: "莲花是一种水生植物，以其高洁的品质和美丽的姿态受到赞美，在东方文化中具有重要象征意义。", tag: "植物,文化,花卉" },
  { filename: "market_stall.png", title: "市场摊位", description: "市场摊位是集市或市场中用于展示和销售商品的临时性销售点，通常出售新鲜农产品、手工艺品等。", tag: "商业,生活,集市" },
  { filename: "microscope_camera_book.png", title: "显微镜、相机和书籍", description: "显微镜用于观察微小物体，相机用于记录图像，书籍提供知识，共同代表了科学研究和学习的工具。", tag: "科学,教育,研究" },
  { filename: "mobility_scooter.png", title: "电动代步车", description: "电动代步车是一种专为老年人或行动不便者设计的电动交通工具，提供便捷的出行方式。", tag: "交通工具,辅助设备,老年人" },
  { filename: "model_car_kit.png", title: "模型车套件", description: "模型车套件是包含组装模型汽车所需所有零件的套装，适合模型爱好者进行拼装和收藏。", tag: "模型,爱好,DIY" },
  { filename: "mongolian_scene.png", title: "蒙古风光", description: "蒙古风光展现了蒙古国独特的自然景观和游牧文化，如广阔的草原、蒙古包和独特的风俗。", tag: "地理,旅游,蒙古" },
  { filename: "newspaper.png", title: "报纸", description: "报纸是定期出版的印刷刊物，包含新闻、评论、广告等内容，是获取信息和了解时事的重要载体。", tag: "媒体,信息,出版" },
  { filename: "nurse_uniform.png", title: "护士制服", description: "护士制服是护士在工作中穿着的统一服装，通常为白色或浅色，代表着专业、卫生和关怀。", tag: "职业,医疗,制服" },
  { filename: "pillow.png", title: "枕头", description: "枕头是睡觉时用于支撑头部和颈部的床上用品，有助于保持舒适的睡姿，改善睡眠质量。", tag: "家居,卧室,睡眠" },
  { filename: "pine_branch.png", title: "松树枝", description: "松树枝是松树的树枝，具有常绿、针叶的特点，常用于园艺装饰或作为节日装饰。", tag: "植物,自然,园艺" },
  { filename: "police_uniform.png", title: "警察制服", description: "警察制服是警察在执行公务时穿着的统一服装，具有识别身份、维护权威和提供保护的作用。", tag: "职业,公共安全,制服" },
  { filename: "pottery_wheel.png", title: "陶艺拉坯机", description: "陶艺拉坯机是一种用于制作陶瓷器皿的设备，通过旋转使泥料成型，是陶艺创作的重要工具。", tag: "艺术,手工,陶瓷" },
  { filename: "rc_car_kit.png", title: "遥控车套件", description: "遥控车套件是包含组装遥控汽车所需零件的套装，适合模型爱好者进行DIY和操控。", tag: "模型,爱好,遥控" },
  { filename: "robotic_arm.png", title: "机械臂", description: "机械臂是一种模仿人类手臂功能的自动化设备，广泛应用于工业生产、医疗和科研领域，实现精准操作。", tag: "机器人,自动化,科技" },
  { filename: "rubiks_cube.png", title: "魔方", description: "魔方是一种三维组合谜题，通过旋转各面使每个面呈现单一颜色，考验逻辑思维和空间想象力。", tag: "玩具,益智,谜题" },
  { filename: "school.png", title: "学校", description: "学校是提供教育的机构，学生在此接受知识、技能和价值观的培养，是社会发展的重要组成部分。", tag: "教育,学习,机构" },
  { filename: "scooter.png", title: "滑板车", description: "滑板车是一种儿童或成人使用的休闲交通工具，通过脚蹬地面或电动机驱动，轻便灵活。", tag: "交通工具,休闲,运动" },
  { filename: "sheep.png", title: "绵羊", description: "绵羊是一种家畜，以其羊毛、羊肉和羊奶而闻名，在全球畜牧业中占有重要地位。", tag: "动物,家畜,农业" },
  { filename: "shoebill_stork.png", title: "鲸头鹳", description: "鲸头鹳是一种大型涉禽，以其独特的鞋状鸟喙而闻名，主要栖息在非洲湿地，是珍稀鸟类。", tag: "动物,鸟类,野生动物" },
  { filename: "skateboard.png", title: "滑板", description: "滑板是一种用于滑板运动的板状工具，通过脚踩和身体平衡进行滑行、跳跃和技巧表演。", tag: "运动,极限运动,板类运动" },
  { filename: "smartphone.png", title: "智能手机", description: "智能手机是集通信、计算、娱乐于一体的便携式设备，具备多功能操作系统和应用程序。", tag: "电子产品,通信,科技" },
  { filename: "soap_dispenser.png", title: "皂液器", description: "皂液器是一种用于分配洗手液或肥皂的装置，常见于浴室和厨房，方便卫生清洁。", tag: "家居,卫浴,清洁" },
  { filename: "soccer_goal.png", title: "足球门", description: "足球门是足球比赛中的得分目标，由两根门柱和一根横梁组成，是足球场的标志性设施。", tag: "运动,足球,体育设施" },
  { filename: "sofa.png", title: "沙发", description: "沙发是一种带软垫的座椅，通常可供多人乘坐，是客厅中常见的家具，提供舒适的休息空间。", tag: "家居,家具,客厅" },
  { filename: "solar_powered_rickshaw.png", title: "太阳能人力车", description: "太阳能人力车是一种结合人力和太阳能辅助动力的交通工具，环保节能，适合城市短途出行。", tag: "交通工具,环保,新能源" },
  { filename: "soup.png", title: "汤", description: "汤是一种以液体为主要成分的食物，通常由水或高汤与各种食材熬煮而成，营养丰富，口感多样。", tag: "食物,烹饪,饮品" },
  { filename: "spain_scene.png", title: "西班牙风光", description: "西班牙风光展现了西班牙独特的自然美景和文化遗产，如高迪建筑、弗拉明戈舞、阳光海岸等。", tag: "地理,旅游,西班牙" },
  { filename: "star_projector.png", title: "星空投影仪", description: "星空投影仪是一种能够将星空图案投射到天花板或墙壁上的设备，营造浪漫或放松的氛围。", tag: "电子产品,家居,娱乐" },
  { filename: "subway_car.png", title: "地铁车厢", description: "地铁车厢是地铁列车的一部分，用于载客，通常在地下隧道或高架轨道上运行，是城市通勤的重要方式。", tag: "交通工具,城市交通,公共交通" },
  { filename: "toaster.png", title: "烤面包机", description: "烤面包机是一种厨房电器，用于烘烤面包片，使其变得金黄酥脆，方便制作早餐。", tag: "厨房电器,家电,早餐" },
  { filename: "tool_kit.png", title: "工具箱", description: "工具箱是用于存放和整理各种工具的盒子或包，便于携带和使用，是家庭维修和专业工作的必备。", tag: "工具,收纳,维修" },
  { filename: "toothbrush.png", title: "牙刷", description: "牙刷是用于清洁牙齿和口腔的工具，通常由刷头和刷柄组成，是日常口腔卫生的重要用品。", tag: "个人护理,卫生,口腔" },
  { filename: "toothpicks.png", title: "牙签", description: "牙签是用于清除牙缝中食物残渣的小木棒或塑料棒，方便口腔清洁，常在饭后使用。", tag: "个人护理,卫生,口腔" },
  { filename: "towel.png", title: "毛巾", description: "毛巾是一种用于擦拭身体、物品的吸水性织物，材质多样，常见于浴室、厨房等场所。", tag: "家居,清洁,纺织品" },
  { filename: "train.png", title: "火车", description: "火车是一种在轨道上运行的交通工具，由火车头牵引多节车厢，用于载客或运货，是重要的陆路运输方式。", tag: "交通工具,运输,铁路" },
  { filename: "tree.png", title: "树", description: "树是一种木本植物，具有坚硬的树干和分枝的树冠，对生态环境和人类生活至关重要。", tag: "植物,自然,生态" },
  { filename: "turkey_landmarks.png", title: "土耳其地标", description: "土耳其地标指土耳其境内具有代表性的自然景观或人文建筑，如圣索菲亚大教堂、卡帕多奇亚热气球等。", tag: "地理,旅游,土耳其" },
  { filename: "usb_charger.png", title: "USB充电器", description: "USB充电器是一种通过USB接口为电子设备充电的电源适配器，广泛应用于手机、平板等便携设备。", tag: "电子产品,充电,数码配件" },
  { filename: "van.png", title: "厢式货车", description: "厢式货车是一种封闭式货车，主要用于运输货物，车厢空间大，常用于物流配送和搬家。", tag: "交通工具,运输,物流" },
  { filename: "wallet.png", title: "钱包", description: "钱包是一种用于存放纸币、硬币、银行卡和身份证件的便携式小包，是日常生活中常用的物品。", tag: "时尚,配饰,生活" },
  { filename: "washing_machine.png", title: "洗衣机", description: "洗衣机是一种用于清洗衣物的家用电器，通过机械力、水流和洗涤剂去除污渍，方便快捷。", tag: "家电,家居,清洁" },
  { filename: "waterfall.png", title: "瀑布", description: "瀑布是河流或溪流从高处垂直跌落形成的自然景观，气势磅礴，是壮丽的自然奇观。", tag: "自然,地理,景观" },
  { filename: "welcome_mat_and_slippers.png", title: "欢迎垫和拖鞋", description: "欢迎垫通常放在门口，用于擦鞋和欢迎客人；拖鞋则是在室内穿着的舒适鞋子，营造居家氛围。", tag: "家居,生活,舒适" },
  { filename: "window_blinds.png", title: "百叶窗", description: "百叶窗是一种由多片叶片组成的窗帘，通过调节叶片角度控制光线和隐私，兼具装饰功能。", tag: "家居,装饰,窗帘" },
  { filename: "wolf.png", title: "狼", description: "狼是一种犬科动物，通常群居，以其强壮、智慧和团队协作能力而闻名，是食物链中的重要捕食者。", tag: "动物,野生动物,哺乳动物" },
  { filename: "wooden_signpost.png", title: "木制路标", description: "木制路标是通常由木材制成的指示牌，用于指示方向、地名或提供信息，常见于自然景区或乡村。", tag: "指示牌,户外,信息" },
  { filename: "airplane.png", title: "飞机", description: "飞机是一种通过发动机产生推力、机翼产生升力从而在空中飞行的航空器，是现代远程交通的重要工具。", tag: "交通工具,航空,旅行" },
  { filename: "anvil.png", title: "铁砧", description: "铁砧是铁匠用来锤打金属的重型铁块，是传统金属加工的重要工具，象征着坚固和工艺。", tag: "工具,金属加工,工艺" },
  { filename: "aye_aye.png", title: "指猴", description: "指猴是一种原产于马达加斯加的夜行灵长类动物，以其独特的细长中指和大型耳朵而闻名。", tag: "动物,灵长类,野生动物" },
  { filename: "badminton_shuttlecock.png", title: "羽毛球", description: "羽毛球是羽毛球运动中使用的球，由羽毛和球托组成，轻巧灵活，是羽毛球比赛的核心。", tag: "运动,器材,羽毛球" }
]; 

export default iconData;
